export default {
  MOVIES: "MOVIES",
  STUDENTS: "STUDENTS",
  TEACHERS: "TEACHERS",
  STUDENTDISCIPLINES: "STUDENTDISCIPLINES",
  TEACHERTDISCIPLINES: "TEACHERTDISCIPLINES",
  VISITS: "VISITS",
  WEEKTYPES: "WEEKTYPES",
  CLASSORDERS: "CLASSORDERS",
};
